inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false